# Generated by Django 3.0.3 on 2020-06-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='date',
        ),
        migrations.RemoveField(
            model_name='day',
            name='text',
        ),
        migrations.AlterField(
            model_name='day',
            name='title',
            field=models.CharField(max_length=20, verbose_name='ペットの名前'),
        ),
    ]
