# Generated by Django 3.0.3 on 2020-06-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0002_auto_20200620_1615'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Day',
            new_name='Pet',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='title',
            new_name='name',
        ),
    ]
