# Generated by Django 3.0.3 on 2020-06-20 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0003_auto_20200620_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
                ('date2', models.DateTimeField(default=django.utils.timezone.now, verbose_name='次回日付')),
            ],
        ),
    ]
