# Generated by Django 3.0.3 on 2020-06-20 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0004_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
        migrations.AddField(
            model_name='pet',
            name='nextdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='次回日付'),
        ),
    ]
