# Generated by Django 3.0.3 on 2020-06-20 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0006_auto_20200620_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='nextdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 11, 43, 3, 168453, tzinfo=utc)),
        ),
    ]
