# Generated by Django 3.0.3 on 2020-06-20 11:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0007_auto_20200620_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='nextdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 11, 55, 10, 935092, tzinfo=utc)),
        ),
    ]
