# Generated by Django 3.0.3 on 2020-06-20 11:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0008_auto_20200620_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='nextdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 11, 56, 56, 191279, tzinfo=utc), verbose_name='次回日付'),
        ),
    ]
