# Generated by Django 3.0.3 on 2020-06-21 03:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0009_auto_20200620_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='nextdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 3, 47, 17, 381575, tzinfo=utc), verbose_name='次回日付'),
        ),
    ]
