# Generated by Django 3.0.3 on 2020-06-21 04:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0010_auto_20200621_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='nextdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 4, 5, 3, 106598, tzinfo=utc), verbose_name='次回日付'),
        ),
    ]
